### ISSUE TITLE
ACS report not work (es)

### ISSUE THREAD

**Issue by ekerjax** [ahmadmuhsen/ogame-acs-split#6]
Hello,

I am trying to read the next report: cr-es-170-a506222869cfebade77296c3ccbb03987684f3df

And shows: The key is invalid. Maybe it isnt work for "es"?

Thanks!!

**Comment by ahmadmuhsen** [comment]
Hi, 
The tool works on all servers, but before it works the OGame team needs to approve and tolerate the tool. until then, we can only use keys from the test servers on https://lobby-pioneers.ogame.gameforge.com
